#!/bin/bash

## Open Applications
FILE="$HOME/.cache/eww_launch.dashboard"
CFG="$HOME/.config/eww/"
EWW=`which eww`

close_dash() {
	${EWW} --config "$CFG" close \
					background profile system clock uptime music github \
					reddit twitter youtube weather apps mail logout sleep reboot poweroff folders
	rm -rf "$FILE"
}

if [[ "$1" == "--ff" ]]; then
	close_dash && firefox &

elif [[ "$1" == "--tg" ]]; then
	close_dash && flatpak run org.telegram.desktop &

elif [[ "$1" == "--dc" ]]; then
	close_dash && flatpak run dev.vencord.Vesktop &

elif [[ "$1" == "--tr" ]]; then
	close_dash && kitty --working-directory ~ &

elif [[ "$1" == "--fm" ]]; then
	close_dash && nautilus ~ &

elif [[ "$1" == "--st" ]]; then
	close_dash && flatpak run com.valvesoftware.Steam &

elif [[ "$1" == "--cd" ]]; then
	close_dash && code &

elif [[ "$1" == "--sp" ]]; then
	close_dash && flatpak run com.spotify.Client &

elif [[ "$1" == "--kr" ]]; then
	close_dash && flatpak run org.kde.krita &

fi
