[[manager.prepend_keymap]]
on = [ "u", "a" ]
run = "plugin yamb --args=save"
desc = "Add bookmark"

[[manager.prepend_keymap]]
on = [ "u", "g" ]
run = "plugin yamb --args=jump_by_key"
desc = "Jump bookmark by key"

[[manager.prepend_keymap]]
on = [ "u", "G" ]
run = "plugin yamb --args=jump_by_fzf"
desc = "Jump bookmark by fzf"

[[manager.prepend_keymap]]
on = [ "u", "d" ]
run = "plugin yamb --args=delete_by_key"
desc = "Delete bookmark by key"

[[manager.prepend_keymap]]
on = [ "u", "D" ]
run = "plugin yamb --args=delete_by_fzf"
desc = "Delete bookmark by fzf"

[[manager.prepend_keymap]]
on = [ "u", "A" ]
run = "plugin yamb --args=delete_all"
desc = "Delete all bookmarks"

[[manager.prepend_keymap]]
on = [ "u", "r" ]
run = "plugin yamb --args=rename_by_key"
desc = "Rename bookmark by key"

[[manager.prepend_keymap]]
on = [ "u", "R" ]
run = "plugin yamb --args=rename_by_fzf"
desc = "Rename bookmark by fzf"

[[manager.prepend_keymap]]
on   = "F"
run  = "plugin smart-filter"
desc = "Smart filter"

[[manager.prepend_keymap]]
on = ["C"]
run = "plugin ouch --args=zip \"$@\""
desc = "Compress with ouch"

[[manager.prepend_keymap]]
on = ["<C-1>"]
run = "plugin --sync toggle-view --args=parent"
desc = "Toggle parent"
[[manager.prepend_keymap]]
on = ["<C-2>"]
run = "plugin --sync toggle-view --args=current"
desc = "Toggle current"
[[manager.prepend_keymap]]
on = ["<C-3>"]
run = "plugin --sync toggle-view --args=preview"
desc = "Toggle preview"

[[manager.prepend_keymap]]
on = [ "M", "m" ]
run = "plugin simple-mtpfs --args=select-then-mount"
desc = "Select device then mount"
[[manager.prepend_keymap]]
on = [ "M", "u" ]
run = "plugin simple-mtpfs --args=select-then-unmount"
desc = "Select device then unmount"
[[manager.prepend_keymap]]
on = [ "g", "m" ]
run = "plugin simple-mtpfs --args=jump-to-device"
desc = "Select device then jump to its mount pt"
[[manager.prepend_keymap]]
on = [ "`", "`" ]
run = "plugin simple-mtpfs --args=jump-back-prev-cwd"
desc = "Jump back to the position before jumped tovice"

